# Generated by Django 5.1.7 on 2025-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("P1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
