# Generated by Django 5.1.7 on 2025-05-02 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("P1", "0002_student_first_name_student_last_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkresult",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr",
                to="P1.homework",
            ),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr",
                to="P1.student",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr",
                to="P1.student",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tr",
                to="P1.test",
            ),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(fields=["date"], name="hw_date_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworkresult",
            index=models.Index(fields=["student"], name="hr_student_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworkresult",
            index=models.Index(fields=["homework"], name="hr_hw_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworkresult",
            index=models.Index(
                fields=["student", "homework"], name="hr_student_hw_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["user"], name="student_user_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"], name="student_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["date"], name="test_date_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["student"], name="tr_student_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["test"], name="tr_test_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["student", "test"], name="tr_student_test_idx"),
        ),
    ]
